"use client";

const REPO = "ms653/Golf-coach";
// Conservative safety margin under the ~8KB query-string limits some
// browsers/servers enforce, leaving room for the title + encoding overhead.
const MAX_URL_LENGTH = 6000;

type Target =
  | "lessons"
  | "sessions"
  | "stats"
  | "reviews"
  | "training_plans"
  | "rounds"
  | "goals";
type Operation = "append" | "update";

interface Props {
  target: Target;
  operation: Operation;
  data: unknown;
  id?: string; // required when operation is "update"
  titleLabel: string; // short human label for the issue title
}

export default function SubmitIssueButton({
  target,
  operation,
  data,
  id,
  titleLabel,
}: Props) {
  const envelope =
    operation === "update" ? { target, operation, id, data } : { target, operation, data };

  const title = `[data] ${target} ${operation}: ${titleLabel}`;
  const json = JSON.stringify(envelope, null, 2);
  const body = [
    "<!-- golf-coach-data:start -->",
    "Auto-generated by the Golf Progress Tracker app. A GitHub Action reads the JSON below, updates the matching /data file, and closes this issue automatically.",
    "",
    "```json",
    json,
    "```",
    "<!-- golf-coach-data:end -->",
  ].join("\n");

  const url = `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(
    title
  )}&body=${encodeURIComponent(body)}`;

  if (url.length > MAX_URL_LENGTH) {
    return (
      <p className="rounded-lg border border-amber-200 bg-amber-50 px-3 py-2 text-sm text-amber-800">
        This entry is too large for automatic submission — use{" "}
        <span className="font-mono">Copy JSON</span> and paste it to Claude instead.
      </p>
    );
  }

  return (
    <a href={url} target="_blank" rel="noopener noreferrer" className="btn-primary">
      Submit via GitHub Issue
    </a>
  );
}
