"use client";

const REPO = "ms653/Golf-coach";

type Target = "lessons" | "sessions" | "stats" | "reviews" | "training_plans";
type Operation = "append" | "update";

interface Props {
  target: Target;
  operation: Operation;
  data: unknown;
  id?: string; // required when operation is "update"
  titleLabel: string; // short human label for the issue title
}

export default function SubmitIssueButton({
  target,
  operation,
  data,
  id,
  titleLabel,
}: Props) {
  const envelope =
    operation === "update" ? { target, operation, id, data } : { target, operation, data };

  const title = `[data] ${target} ${operation}: ${titleLabel}`;
  const body = [
    "<!-- golf-coach-data -->",
    "Auto-generated by the Golf Progress Tracker app. A GitHub Action reads the JSON below, updates the matching /data file, and closes this issue automatically.",
    "",
    "```json",
    JSON.stringify(envelope, null, 2),
    "```",
  ].join("\n");

  const url = `https://github.com/${REPO}/issues/new?title=${encodeURIComponent(
    title
  )}&body=${encodeURIComponent(body)}`;

  return (
    <a href={url} target="_blank" rel="noopener noreferrer" className="btn-primary">
      Submit via GitHub Issue
    </a>
  );
}
